name: qora_devtools_ui
description: "DevTools extension for the Qora state management library"
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.19.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.5.0
  devtools_app_shared: ^0.5.0
  vm_service: ^15.0.2
  qora_devtools_shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
