name: flutter_qora
description: "A Flutter wrapper around the Qora async state management library, providing seamless integration with Flutter's widget tree and lifecycle"
version: 0.0.1
homepage: https://github.com/meragix/qora

publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  qora:
    path: ../qora
  connectivity_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0

# Configuration pour que le package soit considéré comme un package Flutter
flutter: {}
