name: qora_devtools_extension

on:
  push:
    branches: [main]
    paths:
      - "packages/devtools/extension/**"
      - "packages/devtools/shared/**"
      - "packages/dart/**"
      - ".github/workflows/extension.yml"
      - ".github/workflows/_dart_package.yml"
  pull_request:
    paths:
      - "packages/devtools/extension/**"
      - "packages/devtools/shared/**"
      - "packages/dart/**"
      - ".github/workflows/extension.yml"
      - ".github/workflows/_dart_package.yml"

jobs:
  ci:
    uses: ./.github/workflows/_dart_package.yml
    with:
      package: packages/devtools/extension
    secrets: inherit
